// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZGk2RROk5QFyi3_YnwuCIZmnbY41NpNU',
    appId: '1:110593128835:web:18c74af887ea232710deb6',
    messagingSenderId: '110593128835',
    projectId: 'authtutorial-fbf88',
    authDomain: 'authtutorial-fbf88.firebaseapp.com',
    storageBucket: 'authtutorial-fbf88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPlbIxSTAf32qNEezOUVXunXQrZO1IPNI',
    appId: '1:110593128835:android:1088519c912bd0a610deb6',
    messagingSenderId: '110593128835',
    projectId: 'authtutorial-fbf88',
    storageBucket: 'authtutorial-fbf88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBziU5cQEUpGOUwSg3et-OVJVyn28EhT5w',
    appId: '1:110593128835:ios:6da48fbac8b37f5f10deb6',
    messagingSenderId: '110593128835',
    projectId: 'authtutorial-fbf88',
    storageBucket: 'authtutorial-fbf88.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBziU5cQEUpGOUwSg3et-OVJVyn28EhT5w',
    appId: '1:110593128835:ios:6da48fbac8b37f5f10deb6',
    messagingSenderId: '110593128835',
    projectId: 'authtutorial-fbf88',
    storageBucket: 'authtutorial-fbf88.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZGk2RROk5QFyi3_YnwuCIZmnbY41NpNU',
    appId: '1:110593128835:web:6d6ca4c12558584710deb6',
    messagingSenderId: '110593128835',
    projectId: 'authtutorial-fbf88',
    authDomain: 'authtutorial-fbf88.firebaseapp.com',
    storageBucket: 'authtutorial-fbf88.appspot.com',
  );
}
